receivers:
  prometheus:
      config:
        scrape_configs:
          - job_name: app
            scrape_interval: 5s
            static_configs:
              - targets: ['metricgen_east:8000']
            metrics_path: '/'
processors:
  metricstransform:
        transforms:
          - include: .*
            match_type: regexp
            action: update
            operations:
              - action: experimental_scale_value
                experimental_scale: 1
exporters:
  prometheusremotewrite:
    endpoint: http://thanos_receive:19291/api/v1/receive
    external_labels:
      processor: east
  logging:

service:
  telemetry:
     logs:
        level: debug
     metrics:
        #level: detailed
        address: 0.0.0.0:8888
  pipelines:
    metrics/1:
      receivers:  [ prometheus ]
      processors: [ metricstransform ]
      exporters:  [ prometheusremotewrite , logging]
