global:
  http_config: 
    proxy_url: 'http://127.0.0.1:5010'
route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 15s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5010/alerthandler'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
