apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ovm.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      ovm.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ovm.service: grafana
    spec:
      containers:
        - image: grafana/grafana-enterprise
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/grafana/provisioning
              name: grafana-claim0
      restartPolicy: Always
      volumes:
        - name: grafana-claim0
          persistentVolumeClaim:
            claimName: grafana-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ovm.service: grafana
  name: grafana
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    ovm.service: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ovm.service: grafana-claim0
  name: grafana-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
