apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    ovm.service: metricgen2
  name: metricgen2
spec:
  replicas: 1
  selector:
    matchLabels:
      ovm.service: metricgen2
  template:
    metadata:
      labels:
        ovm.service: metricgen2
    spec:
      containers:
        - args:
            - python3
            - demo-metrics-gutentag.py
            - --conf=conf.yaml
            - --port=8001
            - --clientport=5003
            - --nmetrics=100
            - --nlabels=10
            - --duplicate=false
          image: quay.io/observ-vol-mgt/metricgen
          name: metricgen2
          ports:
            - containerPort: 5003
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ovm.service: metricgen2
  name: metricgen2
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5003
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    ovm.service: metricgen2
