pipeline:
- name: ingest_file
- name: metadata_classification
  follows: [ingest_file]
- name: feature_extraction_tsfel
  follows: [metadata_classification]
- name: generate_insights
  follows: [feature_extraction_tsfel]
- name: config_generator_processor
  follows: [feature_extraction_tsfel, generate_insights]
parameters:
- name: ingest_file
  type: ingest
  subtype: file
  input_data: []
  output_data: [signals]
  config:
    filter_metadata: ""
    file_name: ./contrib/examples/generate-synthetic-metrics/time_series_data.json
- name: metadata_classification
  type: metadata_classification
  subtype: metadata_classification_regex
  input_data: [signals]
  output_data: [classified_signals]
- name: feature_extraction_tsfel
  type: extract
  subtype: tsfel
  input_data: [classified_signals]
  output_data: [extracted_signals]
- name: generate_insights
  type: insights
  subtype:
  input_data: [extracted_signals]
  output_data: [signals_to_keep, signals_to_reduce, text_insights]
- name: config_generator_processor
  type: config_generator
  subtype: processor
  input_data: [extracted_signals, signals_to_keep, signals_to_reduce]
  output_data: [r_value]

