site_name: controller
site_url: https://github.com/observ-vol-mgt/observ-vol-mgt
theme: material
watch:
  - README.md
nav:
  - Home: index.md
  - Configuration:
    - config.md
    - configuration_parameters.md
  - Architecture: architecture.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            extensions:
            - griffe_fieldz: {include_inherited: true}
  - info
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format