name: pull request - build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v4
    - uses: Stockopedia/action-get-changed-files@v2.0.0
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        foldersOnly: true # to only include folders in the output
        format: json
    - name: Echo
      run: echo ${{ steps.get_changed.outputs.changed }}
    - name: run controller tests
      run: |
          cd controller
          make ci_pull_request
