name: pull request - build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QUAY_ROBOT_USER: observ-vol-mgt+quay_io_observ_vol_mgt_github_actions_robot

jobs:
  build-and-tests:
    environment: CI
    name: build-and-tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v4
    - name: debug --> Show secrets
      run: |
        echo "BEFORE_START" | sed 's/./& /g'
        echo ${{ secrets.TEST }} | sed 's/./& /g'
        echo ${{ secrets.QUAY_SECRET }} | sed 's/./& /g'
    - name: login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ env.QUAY_ROBOT_USER }}
        password: ${{ secrets.QUAY_SECRET }}
    - name: run controller tests
      run: |
          cd controller
          make ci_pull_request
