name: pull request - build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          controller:
            - 'controller/**'
    - name: run controller tests
      if: steps.changes.outputs.controller == 'true'
      run: |
          cd controller
          make ci_pull_request
