name: pull request - build test and push

on:
  push:
    branches: [ main ]

env:
  QUAY_ROBOT_USER: observ-vol-mgt+quay_io_observ_vol_mgt_github_actions_robot

jobs:
  build-test-push:
    name: build-test-push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v4
    - name: login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ env.QUAY_ROBOT_USER }}
        password: ${{ secrets.QUAY_SECRET }}
    - uses: dorny/paths-filter@v3
      id: controller_changes
      with:
        filters: |
          src:
            - 'controller/**'
    - name: run controller tests
      if: steps.controller_changes.outputs.src == 'true'
      run: |
          cd controller
          make ci_push
    - uses: dorny/paths-filter@v3
      id: manager_configurator_changes
      with:
        filters: |
          src:
            - 'manager/configurator/**'
    - name: push manager configurator image
      if: steps.manager_configurator_changes.outputs.src == 'true'
      run: |
          cd manager/configurator
          make ci_push
    - uses: dorny/paths-filter@v3
      id: manager_alertmanager_changes
      with:
        filters: |
          src:
            - 'manager/alertmanager/**'
    - name: push manager alermanager image
      if: steps.manager_alertmanager_changes.outputs.src == 'true'
      run: |
          cd manager/alertmanager
          make ci_push
    - uses: dorny/paths-filter@v3
      id: processor_changes
      with:
        filters: |
          src:
            - 'processor/**'
    - name: push processor image
      if: steps.processor_changes.outputs.src == 'true'
      run: |
          cd processor
          make ci_push
